site_name: PureFantasy
site_description: 赵纯想个人网站
site_author: 赵纯想
copyright: 赵纯想©️版权所有 2022

nav:
    - 赵纯想: index.md
    - 转山App: 
       - 产品介绍: lifelooper/LifelooperApp.md
       - 用户协议: lifelooper/UserAgreement.md
       - 隐私政策: lifelooper/UserPrivacyPolicy.md
    - 文学创作: 
       - 光谷广场.md
    - 电影《你我皆凡人》: 
       - 电影主页: film/film.md
       - 剧本: film/script.md
    - SwiftUI教程: 
       - 新手课: swiftUI/swiftUINoviceCourse.md
       - 进阶课1-加入Git项目: swiftUI/swiftUIAdvancedCourse1_JoinGit.md


    - 联系方式: contact.md
    
plugins:
    - search:
        lang: ja
    - mkdocs-new-features-notifier
    

