# 自动部署至Leancloud

name: LeanCloudCI

on:
  push:
    branches:
      - main
  page_build:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Github Action 自动部署至 LeanCloud
      uses: enflo/curl-action@v1.2
      with:
        curl: -X POST https://cn-n1-console-api.leancloud.cn/1.1/engine/groups/web/production/version?gitTag=gh-pages&token=NEeccgWTM8M1Pfaxfr9jZOGXTySPC3GzTqHqs0CAGtNE0iYrJQtqMnf4ayv0XJLQ