# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: NextjsBuild

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
  page_build:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
    with:
      node-version: 12.x
  - run: npm install
  - run: npx next build
  - uses: JamesIves/github-pages-deploy-action@3.8.0
    with:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      BRANCH: gh-pages
      FOLDER: out
      CLEAN: true